services:
- type: web
  name: abem-backend
  env: docker
  region: frankfurt
  branch: main
  rootDir: backend
  dockerfilePath: backend/Dockerfile
  envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: config.settings.production
  - key: DJANGO_DEBUG
    value: "False"
  - key: REDIS_URL
    fromService:
      name: abem-redis
      type: redis
      property: REDIS_URL

- type: worker
  name: abem-celery-worker
  env: docker
  region: frankfurt
  branch: main
  rootDir: backend
  dockerfilePath: backend/Dockerfile
  envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: config.settings.production
  - key: DJANGO_DEBUG
    value: "False"
  - key: REDIS_URL
    fromService:
      name: abem-redis
      type: redis
      property: REDIS_URL

- type: redis
  name: abem-redis
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
