# Generated by Django 4.2.16 on 2026-03-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_sender_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
