# Generated by Django 4.2.16 on 2026-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_message_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('payment_confirmed', 'Payment Confirmed'), ('expense_added', 'New Expense Added'), ('expense_updated', 'Expense Updated'), ('user_registered', 'New User Registered'), ('announcement', 'Announcement'), ('message', 'Message')], max_length=30),
        ),
    ]
