# Generated by Django 4.2.16 on 2026-03-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_broadcast_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_broadca_93bfcc_idx',
            old_name='notifications_broadca_idx',
        ),
    ]
