# Generated by Django 4.2.16 on 2026-03-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_add_is_read_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_read_9edb86_idx',
            old_name='notificatio_is_read_pe01_idx',
        ),
    ]
