# Generated by Django 4.2.16 on 2026-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='num_apartments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='num_stores',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
