# Generated by Django 4.2.16 on 2026-03-15 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buildings", "0002_add_num_apartments_num_stores_to_building"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingCoAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Building Co-Admin",
                "unique_together": {("user", "building")},
            },
        ),
        migrations.AddField(
            model_name="building",
            name="co_admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="co_administered_buildings",
                through="buildings.BuildingCoAdmin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
