# Generated by Django 4.2.16 on 2026-03-23 19:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_add_co_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
