# Generated by Django 4.2.16 on 2026-02-23 21:27

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=20)),
                ('floor', models.SmallIntegerField(default=0)),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('store', 'Store')], default='apartment', max_length=15)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('maintenance', 'Under Maintenance')], default='occupied', max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'unit_number'],
            },
        ),
    ]
