# Generated by Django 4.2.16 on 2026-02-23 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.building'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['building'], name='apartments__buildin_f9ce85_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['owner'], name='apartments__owner_i_d3a2b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'unit_number')},
        ),
    ]
