# Generated by Django 4.2.16 on 2026-03-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0003_add_unit_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitinvitation",
            name="registration_code",
            field=models.CharField(
                default="", editable=False, max_length=8, unique=True
            ),
        ),
    ]
