# Generated by Django 4.2.16 on 2026-03-15 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apartments", "0004_add_registration_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="co_owned_apartments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="unitinvitation",
            name="registration_code",
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
