# Generated by Django 4.2.16 on 2026-02-23 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0001_initial'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('split_type', models.CharField(choices=[('equal_all', 'Equal – All Units'), ('equal_apartments', 'Equal – Apartments Only'), ('equal_stores', 'Equal – Stores Only'), ('custom', 'Custom Subset')], default='equal_all', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buildings.building')),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=10)),
                ('next_due', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_config', to='expenses.expense')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='buildings.building')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApartmentExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_expenses', to='apartments.apartment')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_expenses', to='expenses.expense')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('url', models.URLField(max_length=500)),
                ('mime_type', models.CharField(max_length=50)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='expenses_me_entity__27b9c2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['building'], name='expenses_ex_buildin_d47ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['deleted_at'], name='expenses_ex_deleted_75e294_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentexpense',
            index=models.Index(fields=['apartment'], name='expenses_ap_apartme_c24618_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentexpense',
            index=models.Index(fields=['expense'], name='expenses_ap_expense_3735b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apartmentexpense',
            unique_together={('apartment', 'expense')},
        ),
    ]
