# Generated by Django 4.2.16 on 2026-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="color",
            field=models.CharField(
                blank=True,
                default="#2563EB",
                help_text="Hex color for the category badge",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="icon",
            field=models.CharField(
                blank=True,
                default="category",
                help_text="Material icon name (used by web and mobile)",
                max_length=100,
            ),
        ),
    ]
