# Generated by Django 4.2.16 on 2026-03-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_add_icon_color_to_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="expenses.expensecategory",
            ),
        ),
    ]
