# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_add_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_manually_paid",
            field=models.BooleanField(default=False),
        ),
    ]
