# Generated by Django 4.2.16 on 2026-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_add_category_parent'),
        ('payments', '0002_add_building_assets'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_expense_5fcf75_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expense',
        ),
        migrations.AddField(
            model_name='payment',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='payments', to='expenses.expense'),
        ),
    ]
