# Generated by Django 4.2.16 on 2026-03-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_expenses_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingasset',
            name='current_value',
        ),
    ]
